import express from "express";
import path from "path";
import { createServer as createViteServer } from "vite";
import { GoogleGenAI, Type } from "@google/genai";
import dotenv from "dotenv";

dotenv.config();

async function startServer() {
  const app = express();
  const PORT = 3000;

  app.use(express.json({ limit: "5mb" }));

  // Helper to initialize GenAI lazily
  const getGenAI = () => {
    const apiKey = process.env.GEMINI_API_KEY;
    if (!apiKey) {
      throw new Error("GEMINI_API_KEY environment variable is not configured. Please add it to your environment or secrets.");
    }
    return new GoogleGenAI({
      apiKey,
      httpOptions: {
        headers: {
          "User-Agent": "aistudio-build",
        },
      },
    });
  };

  // Health check endpoint
  app.get("/api/health", (_req, res) => {
    res.json({ status: "ok", hasApiKey: !!process.env.GEMINI_API_KEY });
  });

  // API Endpoint: Generate Summary
  app.post("/api/generate-summary", async (req, res) => {
    try {
      const { notes } = req.body;
      if (!notes || typeof notes !== "string" || !notes.trim()) {
        res.status(400).json({ error: "Study notes text is required." });
        return;
      }

      if (notes.trim().length < 20) {
        res.status(400).json({ error: "Please enter more detailed notes (at least 20 characters) for a meaningful summary." });
        return;
      }

      const ai = getGenAI();

      const response = await ai.models.generateContent({
        model: "gemini-3.6-flash",
        contents: `You are an expert AI Study Assistant and Academic Tutor. 
Analyze the provided study notes and create a structured, easy-to-read study guide.

Input Notes:
${notes}`,
        config: {
          responseMimeType: "application/json",
          responseSchema: {
            type: Type.OBJECT,
            properties: {
              title: {
                type: Type.STRING,
                description: "A clear, descriptive title summarizing the subject of these study notes.",
              },
              summary: {
                type: Type.STRING,
                description: "A well-structured markdown summary with headings, bullet points, and key concepts explained clearly.",
              },
              keyTakeaways: {
                type: Type.ARRAY,
                items: { type: Type.STRING },
                description: "5 to 7 essential bullet points or core definitions that the student must remember.",
              },
              studyTips: {
                type: Type.ARRAY,
                items: { type: Type.STRING },
                description: "3 actionable learning tips or memory techniques (e.g. mnemonics, active recall prompts) tailored to this specific content.",
              },
            },
            required: ["title", "summary", "keyTakeaways", "studyTips"],
          },
        },
      });

      const rawText = response.text;
      if (!rawText) {
        throw new Error("No response generated by AI.");
      }

      const parsedData = JSON.parse(rawText);
      res.json(parsedData);
    } catch (err: any) {
      console.error("Error generating summary:", err);
      res.status(500).json({
        error: err.message || "Failed to generate summary. Please check your notes and try again.",
      });
    }
  });

  // API Endpoint: Generate Quiz
  app.post("/api/generate-quiz", async (req, res) => {
    try {
      const { notes } = req.body;
      if (!notes || typeof notes !== "string" || !notes.trim()) {
        res.status(400).json({ error: "Study notes text is required." });
        return;
      }

      if (notes.trim().length < 20) {
        res.status(400).json({ error: "Please enter more detailed notes (at least 20 characters) to generate a quiz." });
        return;
      }

      const ai = getGenAI();

      const response = await ai.models.generateContent({
        model: "gemini-3.6-flash",
        contents: `You are a professional educational assessor. Create an engaging 5-question multiple choice test (MCQ) based directly on the key concepts in these study notes.
Each question MUST have:
- Exactly 4 options.
- Exactly 1 correct answer index (0 for first, 1 for second, 2 for third, 3 for fourth).
- A thorough explanation explaining why the correct answer is right and why others might be incorrect.

Input Notes:
${notes}`,
        config: {
          responseMimeType: "application/json",
          responseSchema: {
            type: Type.OBJECT,
            properties: {
              title: {
                type: Type.STRING,
                description: "A title for the quiz (e.g. 'Photosynthesis & Cellular Respiration Quiz')",
              },
              questions: {
                type: Type.ARRAY,
                items: {
                  type: Type.OBJECT,
                  properties: {
                    id: { type: Type.INTEGER, description: "Question number 1 to 5" },
                    question: { type: Type.STRING, description: "The clear question text" },
                    options: {
                      type: Type.ARRAY,
                      items: { type: Type.STRING },
                      description: "Array of 4 multiple choice options",
                    },
                    correctAnswerIndex: {
                      type: Type.INTEGER,
                      description: "Zero-based index (0, 1, 2, or 3) indicating the correct option",
                    },
                    explanation: {
                      type: Type.STRING,
                      description: "Clear explanation of the correct answer",
                    },
                  },
                  required: ["id", "question", "options", "correctAnswerIndex", "explanation"],
                },
                description: "Exactly 5 multiple-choice questions.",
              },
            },
            required: ["title", "questions"],
          },
        },
      });

      const rawText = response.text;
      if (!rawText) {
        throw new Error("No response generated by AI.");
      }

      const parsedData = JSON.parse(rawText);
      res.json(parsedData);
    } catch (err: any) {
      console.error("Error generating quiz:", err);
      res.status(500).json({
        error: err.message || "Failed to generate quiz. Please try again.",
      });
    }
  });

  // Vite middleware for development vs static serve for production
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), "dist");
    app.use(express.static(distPath));
    app.get("*", (_req, res) => {
      res.sendFile(path.join(distPath, "index.html"));
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`StudyMate AI Server listening on http://0.0.0.0:${PORT}`);
  });
}

startServer();
